### ISSUE TITLE
Can't find 'OpenSearch.Net.Auth.AwsSigV4` package on Nuget

### ISSUE THREAD

**Issue by jonathantsao** [opensearch-project/opensearch-net#110]
### What is the bug?
Unable to find the package `OpenSearch.Net.Auth.AwsSigV4` on Nuget

### How can one reproduce the bug?
Started a new C# .NET6.0 console project and run `dotnet add package OpenSearch.Net.Auth.AwsSigV4`. Output is
```
error: There are no versions available for the package 'OpenSearch.Net.Auth.AwsSigV4'
```

### What is the expected behavior?
Expected to find the package.

### What is your host/environment?
Mac M1

**Comment by Yury-Fridlyand** [comment]
It is not released yet, unfortunately. You can track release progress in https://github.com/opensearch-project/opensearch-build/issues/2635.
