### ISSUE TITLE
[BUG] OpenSearch.Net.Auth.AwsSigV4 not available

### ISSUE THREAD

**Issue by greenpau** [opensearch-project/opensearch-net#112]
### What is the bug?

The documentation says that the following works:

```
<PackageReference Include="OpenSearch.Net.Auth.AwsSigV4" Version="1.0.0" />
```

However, there is not such package on nuget.org.

As the result, the code samples with signing also don't work.

https://github.com/opensearch-project/opensearch-net/blob/main/USER_GUIDE.md#opensearchnetauthawssigv4

**Comment by Yury-Fridlyand** [comment]
It is not released yet, unfortunately. You can track release progress in https://github.com/opensearch-project/opensearch-build/issues/2635.

See also #110

**Comment by greenpau** [comment]
> It is not released yet, unfortunately. You can track release progress in https://github.com/opensearch-project/opensearch-build/issues/2635.

@Yury-Fridlyand , thank you for a quick reply 👍
