### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-net#113]
Adding a release checklist and linking infra issue.

## All CI pass

- [X]  OpenSearch 2.0 is fully supported
- [X]  OpenSearch 1.x is fully supported

## Release Process
https://github.com/opensearch-project/opensearch-net/blob/main/RELEASING.md

- [X] ~~Cut release to infra team~~ Opened https://github.com/opensearch-project/opensearch-build/issues/2635
- [X]  Release branch created for 1.2.0 release
- [X]  Tag created for 1.2.0 release
- []  Release branch created for the next 1.x release

## Post release

- [ ] Update release with release notes
- [ ] Bump version to `1.2.1`

_Originally posted by @harshavamsi in https://github.com/opensearch-project/opensearch-js/issues/303#issuecomment-1267456579_

**Comment by harshavamsi** [comment]
@MaxKsyunz @Yury-Fridlyand could you help create the release branches and tag? We want to release this early next week.

**Comment by Yury-Fridlyand** [comment]
@harshavamsi,
Please, see new tag [v1.2.0](https://github.com/opensearch-project/opensearch-net/releases/tag/v1.2.0) and new branch [1.2.0](https://github.com/opensearch-project/opensearch-net/tree/v1.2.0).
You can get compiled binaries from [CI workflow](https://github.com/opensearch-project/opensearch-net/actions/workflows/release.yml).

**Comment by harshavamsi** [comment]
> @harshavamsi, Please, see new tag [v1.2.0](https://github.com/opensearch-project/opensearch-net/releases/tag/v1.2.0) and new branch [1.2.0](https://github.com/opensearch-project/opensearch-net/tree/v1.2.0). You can get compiled binaries from [CI workflow](https://github.com/opensearch-project/opensearch-net/actions/workflows/release.yml).

Thank you very much for the quick turn-around on this!

**Comment by harshavamsi** [comment]
Closing as 1.2.0 is released.
