### ISSUE TITLE
[BUG] TrackTotalHits does not allow integer input

### ISSUE THREAD

**Issue by EDTCorey** [opensearch-project/opensearch-net#119]
### What is the bug?
When searching, the _TrackTotalHits_ only allows a true / false input, rather than a integer as per Rest Api document.
The opensearch dashboard allows a integer input

### How can one reproduce the bug?
Enter an integer into the _TrackTotalHits_ field within a Search method.

### What is the expected behavior?
A explicit value is able to be set on _TrackTotalHits_

### What is your host/environment?
N/A

### Do you have any screenshots?
![image](https://user-images.githubusercontent.com/102001783/199729208-a4f9bd93-cbeb-4536-be6c-c13967a66df7.png)

### Do you have any additional context?
N/A

**Comment by Xtansia** [comment]
The fix for this bug was included in release [v1.3.0](https://github.com/opensearch-project/opensearch-net/releases/tag/v1.3.0).
