### ISSUE TITLE
[BUG] Cryptographic Issues found by Veracode scan with Insufficient Entropy CWE ID 331

### ISSUE THREAD

**Issue by BangVo** [opensearch-project/opensearch-net#123]
Cryptographic Issues found by Veracode scan with Insufficient Entropy CWE ID [331](https://cwe.mitre.org/data/definitions/331.html)

Detail Veracode Report

Flaw ID: 1233
CWE ID: 331
Severity: Medium
Type: netstandard_dll.System.Random.Next
Source: int <SortNodes>b__48_0(Node) (95% through)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/25688586/205577649-1628772f-bdef-4f8b-85c9-eca5baae2702.png)

**Comment by Xtansia** [comment]
Hi @BangVo, this is not a cryptographic code path, it is just optional randomization of server node ordering in the connection pool.
