### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/opensearch-net#157]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the OpenSearch Net repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| OpenSearch Net | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | Certificate of Origin, Link Checker, Deploy Documentation, License Headers, Changelog Verifier | https://github.com/opensearch-project/opensearch-net/issues/157 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by Yury-Fridlyand** [comment]
There are integration tests with old OpenSearch releases: 
https://github.com/opensearch-project/opensearch-net/blob/8305b2352de61b9e14589624f35b7e8f9760b963/.github/workflows/integration.yml#L15
I think you can check BWC tests.

There are no code coverage checks. Existing tests provide low coverage unfortunately.

**Comment by scrawfor99** [comment]
HI @Yury-Fridlyand, thank you for following up. I will update the notes about the testing and make sure it is accurate.
