### ISSUE TITLE
[FEATURE] Generate API code from OpenSearch API Spec

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/opensearch-net#193]
### Is your feature request related to a problem?
Related to https://github.com/opensearch-project/opensearch-clients/issues/19

### What solution would you like?
Re-use the generator that generates API Code that maintains backwards compatibility with the current client APIs and provides a way to add new APIs.

Old generator was cleaned up in https://github.com/opensearch-project/opensearch-net/commit/7db02e979b19c748879b74485f04f6c352a0d967 so will need reverting and modification.

### What alternatives have you considered?
Using OpenAPI generators instead of re-using the existing generator but it makes it difficult to maintain backwards compatibility.

**Comment by dblock** [comment]
@Xtansia Can we close this?

**Comment by Xtansia** [comment]
@dblock there's still some work remaining to do with:
- updating the generator to work with the latest revisions to the spec
- automating running the generator
- finishing regenerating the existing apis
- generating new apis
- extending generation to req/resp bodies

But I'll split those into new issues close this one
