### ISSUE TITLE
Invalid serialization of a document with a JToken property

### ISSUE THREAD

**Issue by Jyuart** [opensearch-project/opensearch-net#199]
### What is the bug?
A document with a property of type `JToken` doesn't write properly. Instead of getting a nice JSON, I'm getting a bunch of empty square brackets. 

```json
{
  "_index": "test",
  "_id": "xQ5SvocBEGF2UAwoCWfK",
  "_version": 1,
  "_score": 0,
  "_source": {
    "Id": "2b7058e0-44ea-4bbe-a80b-5a253b412470",
    "Name": "Message",
    "Payload": [
      [
        []
      ],
      [
        []
      ],
      [
        []
      ],
      [
        [
          [
            []
          ],
          [
            []
          ]
        ]
      ]
    ]
  }
}
```

### How can one reproduce the bug?
1. Download this [repo](https://github.com/Jyuart/opensearch-jtoken)
2. Run docker compose to have a single OpenSearch node and OpenSearch Dashboard
3. Run dotnet application
4. Go to the dashboard and look for index `test`

### What is the expected behavior?
The `payload` property should contain all the data from the `JToken`

### What is your host/environment?
Windows 11

### Do you have any additional context?
I also tried setting up `JsonNetSerializer`, but the result doesn't change. It's available on [this branch](https://github.com/Jyuart/opensearch-jtoken/tree/jsonnet-serializer)

**Comment by Xtansia** [comment]
@Jyuart this is a result of using the "low-level" `OpenSearch.Net` client which does not use the configured `JsonNetSerializer` when serializing request bodies. This serializes correctly when using the "high-level" `OpenSearch.Client` client like so:
```c#
var connPool = new SingleNodeConnectionPool(new Uri("..."));
var settings = new ConnectionSettings(connPool, JsonNetSerializer.Default);
var client = new OpenSearchClient(settings);

await client.BulkAsync(b => b.Index<object>(i => i.Index("test")
    .Document(new 
    {
        Id = Guid.NewGuid(),
        Name = "Message",
        Payload = JToken.Parse(
            "{\"name\":\"John\",\"age\":30,\"city\":\"New York\",\"contact\":{\"email\":\"john@example.com\",\"phone\":\"+1 123-456-7890\"}}")
    })));
```

**Comment by Jyuart** [comment]
@Xtansia Thank you very much. It worked. 
I assume it's possible to reach the same result with the "low-level" client, but that's probably a lot of work
I'll stick to this solution

Thanks a lot!
