### ISSUE TITLE
Does this fork include the high-level NEST library?

### ISSUE THREAD

**Issue by yuwindr** [opensearch-project/opensearch-net#20]
**Is your feature request related to a problem?**
I have a customer who would like to use a high-level client like NEST on OpenSearch.

**What solution would you like?**
A high-level client similar to NEST to be included in this fork.

**What alternatives have you considered?**
NA

**Do you have any additional context?**
Just wanted to confirm if this fork includes high-level client like NEST.

**Comment by guiangumpac** [comment]
Hi @yuwindr, NEST has been included in this repo and has been renamed to OSC (OpenSearch Client) and can be found in https://github.com/opensearch-project/opensearch-net/tree/main/src/Osc.

**Comment by yuwindr** [comment]
Thank you for the confirmation @guiangumpac!
