### ISSUE TITLE
[ADMIN REQUEST] Update protected branches

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/opensearch-net#210]
The following branch changes need to be made, but I am unable to perform them due to branch protection rules and so require ADMIN intervention:
- `1.x` needs to be fast-forwarded to match `main` as there are breaking changes to be merged and `1.x` is currently very out of date.
- `1.3.0` needs to be updated to match the `v1.3.0` tag at `2b5bb7e27b4d6dc2dec7af1b2aede7986e9ae54d`
- `2.x` needs to be deleted as we have not (yet) released a `2.x` version and it is very out of date (matches `1.0.0` currently)
- `dev-test-nuget-packages` needs to be deleted as it's an old testing branch and was asked to be deleted in https://github.com/opensearch-project/opensearch-net/issues/81#issuecomment-1212503135

@dblock @wbeckler

**Comment by dblock** [comment]
Did all these. Restored branch protection rules.
