### ISSUE TITLE
[PROPOSAL] Lower number of maintainers required to merge from 2 to 1

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-net#226]
### What are you proposing?

Lower the number of maintainers required to merge a PR from 2 to 1.

### What problems are you trying to solve?

There are too few maintainers active and a lot of PRs waiting for weeks.

### What is the developer experience going to be?

PRs approved by 1 maintainer can be merged.

**Comment by dblock** [comment]
@joshuali925 @Xtansia @VachaShah @MaxKsyunz @Yury-Fridlyand wdyt? +1 if you agree?

**Comment by Yury-Fridlyand** [comment]
+1

**Comment by Xtansia** [comment]
👍

**Comment by VachaShah** [comment]
+1

**Comment by dblock** [comment]
Looks like a majority +1, I made the change.
