### ISSUE TITLE
Publish Nuget package

### ISSUE THREAD

**Issue by jamesdoran** [opensearch-project/opensearch-net#25]
Forgive me if this already exists. I searched for `OpenSearch.Net` on nuget.org but couldn't find it.

## What kind of business use case are you trying to solve? What are your requirements?
An easy way for dotnet people to consume this client project.

**What is the problem? What is preventing you from meeting the requirements?**
Needing to pull down code and include a project reference to use the client

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**
Publish a nuget package. It looks like you've already got a packageId defined in the [project file](https://github.com/opensearch-project/opensearch-net/blob/main/src/OpenSearch.Net/OpenSearch.Net.csproj) so may be an additonal build step.

**Comment by sateesh-pagolu** [comment]
Any ETA on this one, team? Also, did anyone else find an alternative that can be used in the interim?

**Comment by alexmeizer** [comment]
Hey @jamesdoran, @sateesh-pagolu, I just added two checklists here that are needed for this release (and subsequent nuget package being publish. You can track the individual progress here:

This is to complete the integration tests: https://github.com/opensearch-project/opensearch-net/issues/27
And this is for the full release (with the nuget): https://github.com/opensearch-project/opensearch-net/issues/14

**Comment by jamesdoran** [comment]
Thanks for the update @alexmeizer

**Comment by jamesdoran** [comment]
Hi guys, it looks like you've released the following 2 packages on nuget.org:
* [OpenSearch.Net](https://www.nuget.org/packages/OpenSearch.Net/)
* [OpenSearch.Net.VirtualizedCluster](https://www.nuget.org/packages/OpenSearch.Net.VirtualizedCluster/)

Thanks very much for your hard work getting these out. 

Do you plan on also releasing [`OpenSearch.Net.Client`](https://github.com/opensearch-project/opensearch-net/tree/main/src/OpenSearch.Client) (OSC)?

**Comment by PaulDMendoza** [comment]
I agree. We really need the OpenSearch.Net.Client (OSC) on Nuget. I just pulled down the source code and I get all sorts of errors so I can't compile this easily myself. 

![image](https://user-images.githubusercontent.com/1039795/172947020-6a524f4a-a9e1-45cd-8e36-680a36bd78a4.png)

**Comment by cray2015** [comment]
@PaulDMendoza its published
https://www.nuget.org/packages/OpenSearch.Net

**Comment by PaulDMendoza** [comment]
Thanks!

**Comment by jamesdoran** [comment]
@cray2015, thanks for this. Nuget is showing:
```
The owner has unlisted this package. This could mean that the package is deprecated, has security vulnerabilities or shouldn't be used anymore.
```
The [`Opensearchproject`](https://www.nuget.org/profiles/opensearchproject) profile on nuget shows no listed packages.

Is there an issue with the existing packages?

**Comment by MaxKsyunz** [comment]
They were unlisted due to #48

**Comment by jamesdoran** [comment]
OK, thanks for the update @MaxKsyunz

**Comment by EDTCorey** [comment]
How long can we expect before the fix from #48 is merged from pre-release to main and the NuGet packages republished?
Cheers

**Comment by jamesdoran** [comment]
Related: [OpenSearch-Build/issues/2025](https://github.com/opensearch-project/opensearch-build/issues/2051)

**Comment by MaxKsyunz** [comment]
The NuGet packages have been published -- https://www.nuget.org/profiles/opensearchproject

Thank you for your patience and understanding.

**Comment by jamesdoran** [comment]
Excellent news! Thanks @MaxKsyunz
