### ISSUE TITLE
[FEATURE] Create releases for 2.x

### ISSUE THREAD

**Issue by samjgalbraith** [opensearch-project/opensearch-net#255]
### Is your feature request related to a problem?
Version 2 of Opensearch has been live for a while now. I can see some merge activity that indicates that some effort may have been made for compatibility with version 2, however, there's no reference or release to back that up. One of our teams has successfully been using the 1.3 .NET client against Opensearch 2.5. It's great that it works for us so far, but it feels a little sketchy that it's not officially supported.

### What solution would you like?
A release of the Opensearch .NET client which explicitly supports Opensearch 2.x and is tested against it.

### What alternatives have you considered?
Taking the risk of using the 1.3 client. It's working so far. But given there's no guarantee of 2.x compatibility, it may break unexpectedly with minor upgrades of Opensearch or the client.

**Comment by Xtansia** [comment]
Hi @samjgalbraith, the client versions do not directly map to the server version supported, it is perfectly safe to use version 1.3 of the client against a 2.x server. The only issues you may run into are features/apis that have not yet been implemented. As part of OpenSearch server's semantic versioning commitment it should not be making any breaking changes between minor versions within the 2.x line.

Integration tests are run against:
- Almost every minor release of OpenSearch including 2.x: https://github.com/opensearch-project/opensearch-net/blob/1.x/.github/workflows/integration.yml#L20-L32
- Upstream unreleased source builds for 1.x, 2.x and future 3.x/main: https://github.com/opensearch-project/opensearch-net/blob/1.x/.github/workflows/integration.yml#L99-L102

The future 2.x release of the client will relate to breaking changes within the client and is unrelated to server changes.

The [COMPATIBILITY.md](https://github.com/opensearch-project/opensearch-net/blob/main/COMPATIBILITY.md) states with version 1.1.0 of the client we began supporting OpenSearch 2.x.

If you have suggestions on how this documentation could be clarified that would be very helpful.

**Comment by samjgalbraith** [comment]
Ah thank you that makes sense and thank you for the prompt response - I was accustomed to the lockstep major versions that are common in related client and server codebases including Elasticsearch prior to Opensearch.
