### ISSUE TITLE
[BUG] Inferred field types ignoring [Nested] and [Keyword] attributes?

### ISSUE THREAD

**Issue by winzig** [opensearch-project/opensearch-net#323]
### What is the bug?

I've found that when using [Nested] and [Keyword] attributes on C# properties, and then indexing them into a non-existent index, when the index is created and the documents are finished indexing, the property exists, but they are not of "nested" or "keyword" types, as if those attributes are being ignored entirely.

If I instead delete the index and recreate it using a `PUT` call with the fields defined explicitly as "keyword" or "nested" then it works fine. 

### How can one reproduce the bug?

Index a document with a `string` property flagged with the `[Keyword]` attribute into a new index, and then do `GET /your-index/_mappings` and you'll see in the results that the field is of type "text" with an inner automatic "keyword" field, instead of just making the top level field of type "keyword". 

### What is the expected behavior?

If you use the `[Keyword]` attribute, the resulting field should be of type "keyword" not of type "text". Similar for `[Nested]`, the resulting property should be of type "nested".

### What is your host/environment?

OpenSearch.Client 1.4.0 connecting to OpenSearch 2.7.0.

### Do you have any additional context?

This is how I'm setting up the client I use to index the documents:

```csharp
ConnectionSettings settings = new ConnectionSettings
(
    new Uri(OurAWSOpenSearchEndpoint), 
    new AwsSigV4HttpConnection()
)
.DefaultFieldNameInferrer
(
    // This is specified as a method that does nothing, so that the field names will
    // remain un-touched, i.e. remain in PascalCase instead of being converted to camelCase.
    fieldName → fieldName
)
.DefaultIndex("messages")
// Set the defaults for the Message object type
.DefaultMappingFor<Message>
(
    m → m
    .IndexName("messages")
    .IdProperty(nameof(Message.MessageKey))
);

#if !RELEASE
settings.EnableDebugMode();
#endif

var client = new OpenSearchClient(settings);
```

**Comment by Xtansia** [comment]
@winzig The auto creation of indices is a behaviour of the server itself, not of the client. So while the server will automatically create a missing index when you make a request to index a document (or bulk index), these requests contain no mapping information, so the server will guess the mappings from the document data. To provide mappings you must explicitly create the index (or update its mappings).

To create an index taking advantage of the attributes you need to do it like so:
```csharp
await client.Indices.CreateAsync("messages", i => i
        .Map(m => m
                .AutoMap<Message>()
        )
);
```

**Comment by winzig** [comment]
What is the point of the attributes then?

**Comment by Xtansia** [comment]
> What is the point of the attributes then?

Primarily any relating to type information/mapping are used to reduce verbosity when creating and index and configuring its mappings.

For example given a type:
```csharp
public class Employee
{
    [Text(Name = "first_name", Norms = false, Similarity = "LMDirichlet")]
    public string FirstName { get; set; }

    [Text(Name = "last_name")]
    public string LastName { get; set; }

    [Number(DocValues = false, IgnoreMalformed = true, Coerce = true)]
    public int Salary { get; set; }

    [Date(Format = "MMddyyyy")]
    public DateTime Birthday { get; set; }

    [Boolean(NullValue = false, Store = true)]
    public bool IsManager { get; set; }

    [Nested]
    [PropertyName("empl")]
    public List<Employee> Employees { get; set; }

    [Text(Name = "office_hours")]
    public TimeSpan? OfficeHours { get; set; }
}
```

You could do:
```csharp
client.Indices.Create("employees", c => c.Map<Employee>(m => m.AutoMap()));
```

Or you could manually build the mappings in fluent syntax:
```csharp
client.Indices.Create("employees", c => c
            .Map<Employee>(m => m
                .Properties(ps => ps
                    .Text(t => t
                        .Name("first_name")
                        .Norms(false)
                        .Similarity("LMDirichlet")
                    )
                    .Text(t => t.Name("last_name"))
                    .Number(n => n
                        .Name(o => o.Salary)
                        .DocValues(false)
                        .IgnoreMalformed()
                        .Coerce()
                    )
                    .Date(d => d
                        .Name(o => o.Birthday)
                        .Format("MMddyyyy")
                    )
                    .Boolean(b => b
                        .Name(o => o.IsManager)
                        .NullValue(false)
                        .Store()
                    )
                    .Nested<Employee>(n => n.Name("empl"))
                    .Text(t => t.Name("office_hours"))
                )
            )
        );
```

Those relating to renaming and formatting of properties and such will also be taken into when performing indexing and searching though.
