### ISSUE TITLE
How can I use .net core to update document in OpenSearch?

### ISSUE THREAD

**Issue by BHJerryChen** [opensearch-project/opensearch-net#339]
Hi Team,

How can I use .net core to update document in OpenSearch? There is no document for this section.

Thanks.

Regards,
Jerry

**Comment by Xtansia** [comment]
Hi @BHJerryChen,

In general you would achieve this with the `OpenSearchClient.Update` method (or `UpdateAsync`).

A very simple example of calling it would be:
```csharp
var resp = await client.UpdateAsync<object>(
            "1234",
            u => u
                .Index("test-index")
                .Doc(new
                {
                    name = "John Doe"
                })
            );
```

Would you be able to give a bit more information about what exactly you're trying to achieve so that I can help you better?
