### ISSUE TITLE
[BUG] AwsSigV4HttpConnection does not respect the AWS SDK logic for credentials selection

### ISSUE THREAD

**Issue by JoshBleggi** [opensearch-project/opensearch-net#363]
### What is the bug?
The documentation for AwsSigV4HttpConnection states that it follows the same logic as the [AWSSDK](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) but it is not finding the configured profile in AwsOptions

### How can one reproduce the bug?
Configure your /.aws/credentials file with a profile other than [default]. Set the value of the Profile in your AwsOptions during dependency injection and configure them via 
`services.AddDefaultAWSOptions(awsOptions);`

Configure the High Level Opensearch Client via dependency injection
```
var openSearchSettings = new ConnectionSettings(new Uri(openSearchConfiguration.OpenSearchNode), new AwsSigV4HttpConnection(awsOptions.Region, service: AwsSigV4HttpConnection.OpenSearchServerlessService)).DefaultIndex(openSearchConfiguration.JobsIndex);
services.AddSingleton<IConnectionSettingsValues>(openSearchSettings);
services.AddSingleton<IOpenSearchClient, OpenSearchClient>();
```

### What is the expected behavior?
The profile configured in AwsOptions should be used on Opensearch Client requests

### What is your host/environment?
Windows 10. .NET 7.0

### Additional Context
It looks like Region is also not automatically picked up from AwsOptions either

**Comment by Xtansia** [comment]
`AWSOptions` is specific to `AWSSDK.Extensions.NETCore.Setup` and not part of the default credential discovery of the core SDK, the OpenSearch client has no integration with those extensions or dependency injection.  

If you were setting the `AWS_PROFILE` environment variable then it would be picked up automatically, otherwise the correct way to achieve this in your code is with:
```csharp
new AwsSigV4HttpConnection(new StoredProfileAWSCredentials(awsOptions.Profile), awsOptions.Region, service: AwsSigV4HttpConnection.OpenSearchServerlessService)
```

**Comment by JoshBleggi** [comment]
AWSOptions is a location that you can find the values set withing AWSConfigs.AWSProfileName. My mistake for referencing a separate domain.

https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html states that Credential discovery is done in order of 
`A credentials profile with the name specified by a value in [AWSConfigs.AWSProfileName](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Amazon/TAWSConfigs.html#properties).`

`A credentials profile with the name specified by the AWS_PROFILE environment variable.`

Either the documentation needs to be updated to state that AwsSigV4HttpConnection only checks environment variables or it should also check the AWSConfigs.

**Comment by Xtansia** [comment]
@JoshBleggi `AWSConfigs` is respected, we use the SDK's `FallbackCredentialsFactory` which does take `AWSConfigs.ProfileName` into account.

The following is correctly picked up by the connection:
```csharp
AWSConfigs.AWSProfileName = "my-profile";
AWSConfigs.AWSProfilesLocation = "/tmp/profiles.conf";
AWSConfigs.RegionEndpoint = RegionEndpoint.APSoutheast2;
var settings = new ConnectionSettings(new Uri("https://..."), new AwsSigV4HttpConnection());
var client = new OpenSearchClient(settings);
```
