### ISSUE TITLE
Is there a way to connect using access key and secret key?

### ISSUE THREAD

**Issue by flgatormike** [opensearch-project/opensearch-net#364]
### What is the bug?
We migrated from elasticsearch to opensearch. While using elasticsearch.net I was able to pass access key and secret key through BasicAwsCredentials, but don't see how I am able to do this with opensearch.net

### What is the expected behavior?
Expect to connect to elasticsearch using access key and secret key.

**Comment by Xtansia** [comment]
Hi @flgatormike, Connecting to AWS hosted services is documented in the user guide: https://github.com/opensearch-project/opensearch-net/blob/main/USER_GUIDE.md#opensearchnetauthawssigv4

**Comment by dblock** [comment]
I have a super minimal demo for this in https://github.com/dblock/opensearch-dotnet-client-demo as well.

**Comment by dblock** [comment]
Looks like the documentation is pretty thorough as well, https://github.com/opensearch-project/opensearch-net/blob/main/USER_GUIDE.md#opensearchnetauthawssigv4, let's close this. @flgatormike feel free to open/comment if you need help.

**Comment by flgatormike** [comment]
so I was able to get it to work like this, thanks everyone!

            var credentials = new BasicAWSCredentials(accessKey, secretKey);
            var connection = new AwsSigV4HttpConnection(credentials, Amazon.RegionEndpoint.USEast1);
            var config = new ConnectionSettings(new Uri(url), connection)
                .DefaultIndex("index")
                .ThrowExceptions(alwaysThrow: true)
                .DisableDirectStreaming()
                .PrettyJson();
                
            _client = new OpenSearchClient(config);
