### ISSUE TITLE
Nuget Packages

### ISSUE THREAD

**Issue by Cris1401** [opensearch-project/opensearch-net#38]
Hello, is this project available at nuget? That would be great. Thanks

**Comment by MaxKsyunz** [comment]
Hi @Cris1401. 

We are working on publishing opensearch .net client on nuget.org. This is tracked under #25.

In the meantime, you can use a release candidate build from [this](https://github.com/opensearch-project/opensearch-net/actions/workflows/release.yml) workflow.

**Comment by Jubilex** [comment]
What is the best way to include the release candidate nupkg in my project?  It is a lambda project which using github webhooks for CI/CD and Codepipeline to build.  I have found no way, short of hosting a nuget package server of referencing the nupkg in my code locally.  Is there something I am missing?

**Comment by MaxKsyunz** [comment]
Hi @Jubilex, yes, at the moment your options are to either host the files yourself temporarily or add them to your repository.

**Comment by TruDan** [comment]
@Jubilex there is another solution, (and its how I currently workaround this issue)

1. Clone/Download a Zip of this repository, you want the contents of "packages" folder somewhere either within your solution's folder, or your somewhere in your system - if it's a git hosted project, obviously within your repo is best. I named my folder "lib".
2. Create/edit a NuGet.config file in the same folder as your `.sln` and add "lib/" as a package source.
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="sln-local" value="lib/" />
  </packageSources>
</configuration>
```

You should end up with something like this:
![image](https://user-images.githubusercontent.com/983207/169107565-39aabaa9-cfdf-4211-acdc-f9e663ac1ff4.png)


3. Now you should be able to find + reference the packages from the nuget tool within your IDE, and have it also work via CI/CD etc :)

Hope this helps!

**Comment by TruDan** [comment]
I wrote it as I was trying it, after I realised that actually I had to
compile the solution first (from the solution folder, I used `dotnet pack
-o <my_lib_dir>` then I could add the package 'Osc'

**Comment by cray2015** [comment]
@TruDan u didnt had to do it. all you had to do was to download the nuget package from the build workflow mentioned in the first thread of this discussion and then add the local location of this package in dotnet nuget sources
`dotnet nuget add source /home/your_username/Downloads/osc_nuget_packages/ -n custom_nuget_packages`
change the source to windows directory style while doing this on windows or you can use the user interface of Visual Studio 

Tools>Nuget Package Manager>Package Manager Settings>Package Sources.

Refer the below Link:
[https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources)

then you can use it like a regular package from Nuget window. Just change the _Package Source_ dropdown to "All"

**Comment by BaldGuitarist** [comment]
This works great. I'm curious as to when you plan to have the nupkg on nuget?

**Comment by nbpeth** [comment]
> We should have the packages In nuget soon.

terrific - this would be very helpful; will be watching

**Comment by dblock** [comment]
Is https://github.com/opensearch-project/opensearch-net/issues/14 a dup?

**Comment by PaulDMendoza** [comment]
> > This works great. I'm curious as to when you plan to have the nupkg on nuget?
> 
> We should have the packages In nuget soon.

What is your definition of "soon"? It's been 2 weeks since you said soon. We really need this package in nuget.

**Comment by dblock** [comment]
I am equally frustrated by this situation. Please follow https://github.com/opensearch-project/opensearch-build/issues/2051.

**Comment by anirudha** [comment]
I posted the current status on the release thread, but I also want to acknowledge, and apologize for failing to provide a regular status update earlier. Thank you for your patience.

https://github.com/opensearch-project/opensearch-build/issues/2051#issuecomment-1208606870

**Comment by MaxKsyunz** [comment]
The packages have been released -- https://www.nuget.org/profiles/opensearchproject
