### ISSUE TITLE
IAM credentials to make connection to OS

### ISSUE THREAD

**Issue by Anishbatajoo** [opensearch-project/opensearch-net#44]
Please provide a sample code that shows how to use IAM credentials to make connection to OS using from .NET client.

**Comment by dblock** [comment]
AFAIK this isn't implemented in the client, contributions welcome!

**Comment by cray2015** [comment]
we tried this approach with [elasticsearch-net-aws](https://github.com/bcuff/elasticsearch-net-aws). we were hoping this would work as well but the parameters were not accepted. ultimately had to resort to the internal users. we wanted to implement Document level security while using AWS cognito and OS roles.

**Comment by gabe4797** [comment]
@cray2015 I was able to get this to work by basically copying everything from Elasticsearch.Net.Aws in [elasticsearch-net-aws](https://github.com/bcuff/elasticsearch-net-aws) to a new project, and removing the reference to Elasticsearch.Net while adding a reference to OSC (I added the nuget package to my own CodeArtifact repo until released to NuGet [artifacts](https://github.com/opensearch-project/opensearch-build/issues/2051#issue-1218987401)

**Comment by cray2015** [comment]
@gabe4797 can you share a working example maybe?

**Comment by gabe4797** [comment]
@cray2015 Usage is the same as the elasticsearch-net-aws. You just have to update the reference to yet to be released osc.

**Comment by cray2015** [comment]
Alright I will try again! thanks for the confirmation. Also can you share your email or any social where I can discuss more on this? I have a few other queries. you will be extremely helpful! so please
