### ISSUE TITLE
Sample code on how to use ApiKeyAuthentication

### ISSUE THREAD

**Issue by LYDE1234** [opensearch-project/opensearch-net#45]
How do you obtain the API key for ApiKeyAuthentication? I can't see a programmatic way in the API. Please provide sample code or point to some if already there.

**Comment by acarbonetto** [comment]
Is there documentation you can refer to, please?  If you're looking for ways to use IAM Authorization in the client, please see: [44](https://github.com/opensearch-project/opensearch-net/issues/44)

**Comment by wbeckler** [comment]
The OpenSearch server doesn't have this feature yet: https://github.com/opensearch-project/security/issues/1504
