### ISSUE TITLE
[FEATURE] Nuget of opensearch client supporting PIT

### ISSUE THREAD

**Issue by us9898** [opensearch-project/opensearch-net#452]
### Is your feature request related to a problem?
The latest version of opensearch client 1.5 does not have support for point in time. I see that it is already supported in main
when is the release for 1.6 so that PIt becomes available?

### What solution would you like?
Requesting a release of new version of opensearch client nuget which supports PIT? Any date which has been announced.

**Comment by Xtansia** [comment]
Hi @us9898,

I'm looking to get a 1.6.0 version out in the coming days that will include this

**Comment by us9898** [comment]
@Xtansia ,
thanks for the response, any tentative date you have in mind.
Sorry for rushing this.

**Comment by us9898** [comment]
@Xtansia ,
Thank you

**Comment by Xtansia** [comment]
@us9898 v1.6.0 is now available on NuGet containing point-in-time support. Please let me know if you run into any issues.

**Comment by us9898** [comment]
thank you
@Xtansia
