### ISSUE TITLE
[FEATURE] AWS Personalize Plugin integration query

### ISSUE THREAD

**Issue by sarboz** [opensearch-project/opensearch-net#483]
I wanted to use aws personalize plugin to re-rank search results. In AWS [documentation](https://docs.aws.amazon.com/personalize/latest/dg/opensearch-personalizing-results.html) we see that we can achieve this through  **ext**  section in the request, But I couldn't find such an option in .net client. 
```
 "ext": {
        "personalize_request_parameters": {
            "user_id": "USER ID"
            "context": { "DEVICE" : "mobile phone" }
        }
    }
```

Is there any way to use that plugin with .net client?

**Comment by dblock** [comment]
I think this is a feature request. You can always use the lower level HTTP API, https://github.com/opensearch-project/opensearch-net/blob/main/guides/json.md as a last resort, but if you have time maybe contribute these options to the higher level DSL?

**Comment by Xtansia** [comment]
This should be relatively simple to implement if we treat `ext` as an arbitrary dictionary field, it'd be the same as the `_meta` field on templates:
https://github.com/opensearch-project/opensearch-net/blob/main/src/OpenSearch.Client/Cluster/ComponentTemplate/ComponentTemplate.cs#L23-L25
https://github.com/opensearch-project/opensearch-net/blob/main/src/OpenSearch.Client/Cluster/ComponentTemplate/PutComponentTemplateRequest.cs#L20
https://github.com/opensearch-project/opensearch-net/blob/main/src/OpenSearch.Client/Cluster/ComponentTemplate/PutComponentTemplateRequest.cs#L27
https://github.com/opensearch-project/opensearch-net/blob/main/src/OpenSearch.Client/Cluster/ComponentTemplate/PutComponentTemplateRequest.cs#L31-L34

So then it'd be something like:
```csharp
await client.SearchAsync(s => s
    .Ext(e => e
        .Add(
            "personalize_request_parameters",
            new
            {
                user_id = "USER_ID",
                context = new { DEVICE = "mobile phone" }
            }
        )
    )
);
```

**Comment by kevin-donovan-zocdoc** [comment]
We are in need of a feature like this. We can use the low level client as a workaround but we prefer to use the high level client to take advantage of the extra features in there and for the type checks.
