### ISSUE TITLE
[BUG] Region is lost for AwsSigV4HttpConnection when using AssumeRoleAWSCredentials upon token refresh

### ISSUE THREAD

**Issue by isaacws** [opensearch-project/opensearch-net#490]
### What is the bug?
Given a basic aws credential that assumes a role for access to an Opensearch serverless endpoint, when the access token refreshes then I find logs trying to access "GET 169.254.169.254/latest/dynamic/instance-identity/document" which times out causing latency in my application. This indicates that the region is not being found on the token refresh and the credential search is trying to find the region and finally failing to query EC2 instance metadata. This introduces 5 seconds of latency on these token refresh requests. The app still continues to work and the token does refresh but the region search causes issues in my logs and latency in the application. The region search behavior is found in the following file. https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AWSRegion.cs#L179

### How can one reproduce the bug?
```
//Ensure that credentials are not in the environment or profile but just passed in via strings.
var awsCredential = new BasicAWSCredentials(credentials.AccessKey, credentials.Secret);
var newCredentials = new AssumeRoleAWSCredentials(
                                                       awsCredential,
                                                       roleArn,
                                                       "opensearch-session");
var connection = new AwsSigV4HttpConnection(newCredentials, RegionEndpoint.USEast2, "aoss");
var connectionSettings = new ConnectionSettings(endpointUri, connection);
var openSearchClient = new OpenSearchClient(connectionSettings);
//wait for token refresh to occur.
```

### What is the expected behavior?
When using an AssumeRoleAWSCredential and specifying the region on creation of the AwsSigV4HttpConnection, token refreshes should pull the region from that specified in the AwsSigV4HttpConnection.

### What is your host/environment?
Windows Server 2019

### Do you have any additional context?
Token refresh for assumed credentials appears to happen hourly.
**Current work around:**
Set the AWS_REGION environment variable so that the fall through region search finds something. This is less than optimal when utilizing multiple AWS credentials and regions.
Opened bug with SDK team as well but was pointed to here as it appears it is the SigV4 connection not maintaining the region.
https://github.com/aws/aws-sdk-net/issues/3135

**Comment by Xtansia** [comment]
We have no control over the behaviour of `AssumeRoleAWSCredentials`, and there's no mechanism by which it could pick up the region from `AwsSigV4HttpConnection` without us overwriting the global application level region. Setting `AWS_REGION` is AWSSDK.Net's intended mechanism for setting this, but you could make a request to them for allowing providing an explicit region to `AssumeRoleAWSCredentials`.

The region provided to `AwsSigV4HttpConnection` (or picked up from env) is only used for signature calculations and nothing else.

**Comment by isaacws** [comment]
Thank you for the clarification and reasoning here. I commented back to the SDK team and hopefully it can be addressed there.
