### ISSUE TITLE
[BUG] Specifying property as search as you type and keyword (for sorting) results in index property only having search as you type?

### ISSUE THREAD

**Issue by kknd4eva** [opensearch-project/opensearch-net#518]
### What is the bug?

My index is defined as follows: 

```
                var createIndexResponse = await _client.Indices.CreateAsync("salesorders", c => c
                     .Map<SalesOrder>(m => m
                         .AutoMap()
                         .Properties(ps => ps
                             .SearchAsYouType(s => s
                                 .Name(n => n.OrderReference)
                                 .Fields(fs => fs
                                     .Keyword(k => k
                                         .Name("keyword")
                                     )
                                 )
                             )
                             .SearchAsYouType(s => s
                                 .Name(n => n.CustomerName)
                                 .Fields(fs => fs
                                     .Keyword(k => k
                                         .Name("keyword")
                                     )
                                 )
                             )
                             .Nested<SalesOrderItem>(n => n
                                 .Name(nm => nm.LineItems)
                                 .AutoMap() // Auto map the properties of SalesOrderItem
                                 .Properties(pps => pps
                                     .SearchAsYouType(s => s
                                         .Name(nn => nn.ActiveIngredients)
                                         )
                                    .SearchAsYouType(s => s
                                        .Name(nn => nn.Sku)
                                    )
                                    .Number(n => n
                                        .Name(nn => nn.BackorderQuantity)
                                        .Type(NumberType.Integer)
                                     )
                                 )
                             )
                         )
                     )
                );
```

But the resulting index shows OrderReference field as only a search as you type field? E.g. 
```

        "orderReference": {
          "type": "search_as_you_type",
          "doc_values": false,
          "max_shingle_size": 3
        },
        "orderSource": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "orderStatus": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
```

### How can one reproduce the bug?
Create an index
Specify a field as both SearchAsYouType and Fields > KeyWord

### What is the expected behavior?
The field is indexed to support partial match/search as well as being a field for sorting.

### What is your host/environment?
Locally Windows 10. 
AWS Lambda for cloud. 

### Do you have any screenshots?
N/A

### Do you have any additional context?
Error message: 

```
# Request:
{"from":0,"query":{"bool":{"must":[{"range":{"created":{"gte":"2023-10-23T20:10:23","lte":"2023-12-23T20:10:23"}}},{"term":{"orderStatus.keyword":{"value":"ACC_ERROR"}}}]}},"size":1,"sort":[{"orderReference.keyword":{"order":"asc"}}],"_source":{"includes":["created","orderReference","customerRef","paymentAmount","orderType","orderSource","userCreated","orderStatus"]}}
# Response:
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [orderReference.keyword] in order to sort on",
```

**Comment by Xtansia** [comment]
This appears to be a behaviour of the OpenSearch cluster, rather than specific to the .NET client. That the `search_as_you_type` mapping doesn't allow setting sub-fields.

Running the following in the dashboard devtools:
```
PUT sayt_test
{
  "mappings": {
    "properties": {
      "foobar": {
        "type": "search_as_you_type",
        "fields": {
          "keyword": {
            "type": "keyword"
          }
        }
      }
    }
  }
}

GET sayt_test/_mapping
```
Results in the same behaviour as your issue, without the keyword field:
```
{
  "sayt_test": {
    "mappings": {
      "properties": {
        "foobar": {
          "type": "search_as_you_type",
          "doc_values": false,
          "max_shingle_size": 3
        }
      }
    }
  }
}
```

However it seems like if you use `text` or `keyword` as the primary, you can use `search_as_you_type` as a sub-field:
```
PUT sayt_test
{
  "mappings": {
    "properties": {
      "foobar": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword"
          },
          "suggestion": {
            "type": "search_as_you_type"
          }
        }
      }
    }
  }
}

GET sayt_test/_mapping
```

Resulting in:
```
{
  "sayt_test": {
    "mappings": {
      "properties": {
        "foobar": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            },
            "suggestion": {
              "type": "search_as_you_type",
              "doc_values": false,
              "max_shingle_size": 3
            }
          }
        }
      }
    }
  }
}
```

**Comment by kknd4eva** [comment]
@Xtansia thank you SO much for the fast response. I hope you don't mind me asking as it's outside the bounds of this being a bug, but how did you know that this was the problem? I have looked at Opensearch documentation and I couldn't see anything that specified that certain field types must be primary versus a sub field? Maybe I just missed something?

**Comment by Xtansia** [comment]
> @Xtansia thank you SO much for the fast response. I hope you don't mind me asking as it's outside the bounds of this being a bug, but how did you know that this was the problem? I have looked at Opensearch documentation and I couldn't see anything that specified that certain field types must be primary versus a sub field? Maybe I just missed something?

This was primarily just from experimentation while validating if it's behaviour that _should_ work before digging into the client. 

There doesn't appear to be any specific documentation covering this case specifically. Only hint I found in my quick search is that the [`text` docs do specify the `fields` parameter being supported](https://opensearch.org/docs/2.11/field-types/supported-field-types/text/#parameters), but the [`search_as_you_type` docs omit the `fields` parameter](https://opensearch.org/docs/2.11/field-types/supported-field-types/search-as-you-type/#parameters).

Feel free to raise this on the https://github.com/opensearch-project/opensearch or https://github.com/opensearch-project/documentation-website repos depending on whether you want to clarify that this is intentional or have it documented. As it seems odd that it does not error when specifying `fields` on `search_as_you_type` if it's completely unsupported.

**Comment by kknd4eva** [comment]
Thanks again for your help, I will review those repos and raise it in the most appropriate one.  I am new to OpenSearch, so am working my way through its complexities :)
