### ISSUE TITLE
[BUG] Unable to set slices to auto in .Net Opensearch client

### ISSUE THREAD

**Issue by goldenc** [opensearch-project/opensearch-net#550]
### What is the bug?
When doing a reindex I want to set slices to auto but the api only allows me to set a nullable long

```
///<summary>The number of slices this task should be divided into. Defaults to 1, meaning the task isn't sliced into subtasks. Can be set to `auto`.</summary>
		public long? Slices
		{
			get => Q<long? >("slices");
			set => Q("slices", value);
		}
```

### How can one reproduce the bug?
Try and reindex with slices set to auto with the Opensearch .net client (1.6.0)

### What is the expected behavior?
Be able to specify auto slices

### What is your host/environment?
Linux

### Do you have any screenshots?
No

**Comment by Xtansia** [comment]
Hi @goldenc,

Thank you for reporting this! It appears that when the client code was generated the spec used only specified `slices` as an integer, not that it also accepts the string `auto`. I will look into a good way to represent this and make a bugfix.

In the meantime you should be able to work around this by taking advantage of the "raw" request methods:
```csharp
var response = await client.Http.PostAsync<ReindexOnServerResponse>(
            "/_reindex",
            d => d
                .SerializableBody(new
                {
                    source = new
                    {
                        index = "source-index"
                    },
                    dest = new
                    {
                        index = "dest-index"
                    }
                })
                .QueryString(qs => qs.Add("slices", "auto")));
```

**Comment by goldenc** [comment]
ok, thanks for the workaround 👍
