### ISSUE TITLE
[BUG] S3 snapshot repositories without settings fail to deserialize

### ISSUE THREAD

**Issue by drewfead** [opensearch-project/opensearch-net#573]
### What is the bug?
When listing snapshot repositories using `Snapshot.GetRepositoryAsync()`, s3 repositories without settings can't be deserialized.

### How can one reproduce the bug?
Using an AWS opensearch domain (not serverless) running version OpenSearch_2_11_R20231113-P3, when I send this request:

`GET ***.es.amazonaws.com/_snapshot/_all?pretty`

I get a response like this (some data redacted):

```
{
    "cs-automated": {
        "type": "s3"
    },
    "authoring-service-snapshots": {
        "type": "s3",
        "settings": {
            "bucket": "...",
            "region": "us-west-2",
            "role_arn": "..."
        }
    }
}
```

The `cs-automated` snapshot repository seems to have been created on my behalf by AWS, and is therefore presumably valid.

Using this call defined by the `IOpenSearchClient`, using version 1.7.0:
```
GetRepositoryResponse? listRepositories = await _client.Snapshot.GetRepositoryAsync(
    ct: cancel
);
```

The call fails with the exception message `Cannot create an instance of OpenSearch.Client.S3Repository because it has no constructor taking 0 arguments.`

### What is the expected behavior?
A `GetRepositoryResponse` would be returned successfully containing two `S3Repository`s in its `Repositories` dictionary, one with either null or empty settings, and the other with appropriately populated settings.

### What is your host/environment?
I have seen the same issue locally using macOS and in the deployed environment running on x86 and arm ec2 instances (in a container).

### Do you have any screenshots?
N/A

### Do you have any additional context?
It seems to hit this condition: https://github.com/opensearch-project/opensearch-net/blob/df71677574067161c204a4b5e58f25d9442d88ac/src/OpenSearch.Client/Snapshot/Repositories/GetRepository/GetRepositoryResponseFormatter.cs#L144-L145
and attempts to invoke a constructor by reflection that doesn't exist.

As a workaround I've tried listing all of the repositories besides `cs-automated` using the [documented support for exclude pattern](https://opensearch.org/docs/latest/api-reference/snapshots/get-snapshot-repository/#path-parameters), but it doesn't work as expected on the server-side. I.e.

```
GET ***.es.amazonaws.com/_snapshot/*,-cs-automated?pretty
```

results in the following response
```
{
    "error": {
        "root_cause": [
            {
                "type": "repository_missing_exception",
                "reason": "[-cs-automated] missing"
            }
        ],
        "type": "repository_missing_exception",
        "reason": "[-cs-automated] missing"
    },
    "status": 404
}
```

Since this area in the opensearch documentation is sparse, please advise if my query format expectations are wrong (there are no relevant examples of using exclude patterns in the official docs).

**Comment by Xtansia** [comment]
@drewfead A fix for this has now been released as v1.7.1, it'd be great if you could confirm if this solves your issue?
