### ISSUE TITLE
[BUG] No MinScore property exposed on ScriptScore query

### ISSUE THREAD

**Issue by SamuelCox** [opensearch-project/opensearch-net#622]
### What is the bug?
The docs specify an optional MinScore property https://opensearch.org/docs/latest/query-dsl/specialized/script-score/

Unless I am missing something, there is no method to specify this in opensearch.client

### How can one reproduce the bug?
``` var kNNQueryDescriptor = new ScriptScoreQueryDescriptor<Product>();

 if (searchCriteria.Embedding == null || searchCriteria.Embedding.Length == 0)
 {
     return kNNQueryDescriptor;
 }

 kNNQueryDescriptor
     .Query(q => q.Bool(x => x.Must(y => y.Term(f => f.SoldOut, false))))
     .Script(s => s.Source("knn_score")
                   .Lang("knn")
                   
                   .Params( new Dictionary<string, object> {
                       { "field", "searchableTextEmbedding" }, 
                       { "query_value", searchCriteria.Embedding }, 
                       { "space_type", "cosinesimil" } 
                   }));

 return kNNQueryDescriptor;
```
 
 Where in above can I set the MinScore property?

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
Windows 11

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-net/assets/6514954/8d65ef5d-6bc9-4b66-9780-6f8feedd4940)
![image](https://github.com/opensearch-project/opensearch-net/assets/6514954/fdb5ae36-b709-45bf-82fe-73fb6acf8699)
![image](https://github.com/opensearch-project/opensearch-net/assets/6514954/caf737f8-1adc-4a52-84bb-8f50b46fd464)

### Do you have any additional context?
_Add any other context about the problem._

**Comment by Xtansia** [comment]
Thanks for the report @SamuelCox. Would you be interested in creating a PR to add this? It should mostly just be a matter of adding the `double? MinScore` property to the classes in this file: https://github.com/opensearch-project/opensearch-net/blob/main/src/OpenSearch.Client/QueryDsl/Specialized/ScriptScore/ScriptScoreQuery.cs

**Comment by SamuelCox** [comment]
Yeah very happy to, when I get a spare moment.
