### ISSUE TITLE
[BUG] Flaky test GitHubIssue5432.cs | OpenSearch.Net.UnexpectedOpenSearchClientException : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SamuelCox** [opensearch-project/opensearch-net#653]
### What is the bug?
This test sometimes fails on CI runs, see: https://github.com/opensearch-project/opensearch-net/actions/runs/9163989095/job/25194291570?pr=638

It seems similar to some other flaky tests
https://github.com/opensearch-project/opensearch-net/issues/626

### How can one reproduce the bug?
Run a ci cd pipeline

### What is the expected behavior?
The test should consistently pass

### What is your host/environment?
Ubuntu 22.04.4
Version 20240516.1.0

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

**Comment by Xtansia** [comment]
After investigation 5432 isn't flaky, it's caused by another test: #657
