### ISSUE TITLE
[BUG]Wrong reference to StaticConnectionPool in User Guide

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/opensearch-net#67]
**What is the bug?**
In the User Guide, StaticConnectionPool is referenced as StaticNodePool.

**How can one reproduce the bug?**
In the User Guide/"Connecting to multiple nodes using a connection pool" section, there is the following line:

var pool = new StaticNodePool(nodes);

**What is the expected behavior?**

It should be:

var pool = new StaticConnectionPool(nodes);

**What is your host/environment?**
 N/A

**Do you have any screenshots?**
![image](https://user-images.githubusercontent.com/105444904/181347712-e3f83793-dd2d-414f-9c84-44dbe8d81bd1.png)

**Do you have any additional context?**
N/A

**Comment by dblock** [comment]
Is this in https://github.com/opensearch-project/documentation-website? Feel free to fix!

**Comment by kolchfa-aws** [comment]
It is not. It is in https://github.com/opensearch-project/opensearch-net/.
