### ISSUE TITLE
[FEATURE] Serialize DateOnly as a date instead of serializing its properties individually

### ISSUE THREAD

**Issue by nalka0** [opensearch-project/opensearch-net#680]
### Is your feature request related to a problem?
DateOnly properties are treated as any other complex type and its properties are serialised individually. It prevents using features like date ranges when searching.

### What solution would you like?
DateOnly properties be treated as DateTime properties, except maybe they'd use a different format (like `yyyy-mm-dd`)

### What alternatives have you considered?
Customizing the serialization behavior myself, but I didn't find a way to do so. Also tried applying [DateAttribute] to my property but didn't seem to change anything

### Do you have any additional context?
Currently [DateOnly](https://learn.microsoft.com/en-us/dotnet/api/system.dateonly) properties are serialized this way :
```json
"dateOnlyProperty": {
    "year": 2024,
    "month": 4,
    "day": 15,
    "dayOfWeek": 1,
    "dayOfYear": 106,
    "dayNumber": 738990
},
```

PS : `TimeOnly` may have the same kind of issues

**Comment by Xtansia** [comment]
Thanks for reporting this @nalka0! Would you be interested in contributing a fix for this? It should just involve adding a `JsonFormatter` [similar to the DateTime & co ones](https://github.com/opensearch-project/opensearch-net/blob/main/src/OpenSearch.Net/Utf8Json/Formatters/DateTimeFormatter.cs) then registering like [here](https://github.com/opensearch-project/opensearch-net/blob/efbae03cc73e464ab3a68b21fd2ca914df2b667b/src/OpenSearch.Net/Utf8Json/Resolvers/BuiltinResolver.cs#L117). It will require adding the minimum necessary .NET version (I think 6? as I believe it's not in .netstandard2.0) as a target framework and then using `#if`s to conditionally add in the formatter depending on target .NET version.

**Comment by nalka0** [comment]
@Xtansia Honnestly, I don't feel familiar enough with either OpenSearch nor this nuget package to feel like sending a pull request 😅 
I also am not so familiar with the .Net version management you described but can confirm DateOnly has been introduced in .Net 6 and isn't in .Net standard

**Comment by Xtansia** [comment]
@nalka0 That's completely understandable and no problem :)

**Comment by joefeser** [comment]
I am going to attempt a PR for this one

**Comment by nalka0** [comment]
I guess this issue should be reopened (can't do it myself) based on the problems I described on the related PR https://github.com/opensearch-project/opensearch-net/pull/734#issuecomment-2275492813

**Comment by joefeser** [comment]
@nalka0 If you can reach out to me (see contact info), I can work with you to ensure everything works as expected.

**Comment by nalka0** [comment]
> @nalka0 If you can reach out to me (see contact info), I can work with you to ensure everything works as expected.

I'm sorry, what contact info are you talking about ? I don't see any 😅

**Comment by joefeser** [comment]
Sorry I realized I took my email off my profile. @nalka0 joseph dot Feser at the google email service.
