### ISSUE TITLE
[BUG] Setup branch protection rules 

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-net#71]
Setup branch protection rules for this repository inline with opensearch-project. 

- Looks like the `main` branch doesn't require approvals. 
- Setup CODEOWNERS.md

**Comment by VachaShah** [comment]
@saratvemulapalli I added the branch protection rules. Looks like CODEOWNERS file already exists. Is there anything else that is needed?

**Comment by saratvemulapalli** [comment]
@VachaShah perfect thank you.
