### ISSUE TITLE
[BUG] BulkAlias summary saying it calls indices.stats

### ISSUE THREAD

**Issue by jumc** [opensearch-project/opensearch-net#715]
### What is the bug?
Method summary informs wrong API call. 

### How can one reproduce the bug?
Look at BulkAlias(Func<BulkAliasDescriptor, IBulkAliasRequest> selector) docs through an IDE

### What is the expected behavior?
```
/// <summary>
/// <c>POST</c> request to the <c>indices.update_aliases</c> API, read more about this API online:
/// <para></para>
/// <a href = "https://opensearch.org/docs/latest/opensearch/rest-api/alias/">https://opensearch.org/docs/latest/opensearch/rest-api/alias/</a>
/// </summary>
public BulkAliasResponse BulkAlias(Func<BulkAliasDescriptor, IBulkAliasRequest> selector) => BulkAlias(selector.InvokeOrDefault(new BulkAliasDescriptor()));		
```

### Do you have any screenshots?
![image](https://github.com/user-attachments/assets/e9b344f9-5d3f-46b9-adaa-1fc7d41753bd)

**Comment by dblock** [comment]
Thanks @jumc, want to fix it?

**Comment by jumc** [comment]
Sure! Here's the PR: #717 
Since this is my first time contributing, please let me know if I'm missing something

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/opensearch-net/pull/717.
