### ISSUE TITLE
[BUG] Invalid response on Bulk actions after success

### ISSUE THREAD

**Issue by brendanjeffreymcmahon** [opensearch-project/opensearch-net#72]
**What is the bug?**
When making a `bulk` request of any kind (`client.Bulk`, `client.BulkAsync`, `client.BulkAll`), the response is:
```
Invalid OpenSearch.Client response built from a successful (200) low level call on POST
```
along with a list of "errors", all of which appear to be blank. The actual indexing works, but the response still says "Invalid" for seemingly no reason.

**How can one reproduce the bug?**
1. Create a new OpenSearchClient
2. Generate some data to index
3. Call a bulk indexing command on the client (eg. `var bulkResponse = await client.BulkAsync(selector => selector.Index(indexName).IndexMany<Account>(accts));`
4. Parse the response message

**What is the expected behavior?**
The response message should read "Valid OpenSearch.Client response built from a successful (200) low level call on POST"

**What is your host/environment?**
 - OS: Windows 10 running OpenSearch in Docker. Attempted in both .NET Framework 4.7.2 and .NET Core 6
 - Version 1.0.0

**Do you have any screenshots?**
I can provide a screenshot if it's helpful

**Do you have any additional context?**
My method for testing this was to:
1. Delete the existing index with a given name
2. Validate no data has been indexed to that index
3. Run the code to Bulk Index
4. Validate that the Index has been created and populated with the expected data

It's entirely possible that I'm misunderstanding the response and there is in fact a reason it's labeled "invalid," but it's not clear to me and it appears to work from my perspective.

**Comment by MaxKsyunz** [comment]
@brendanjeffreymcmahon what version of OpenSearch are you testing against?

I can reproduce this issue against OpenSearch 2.x.

The current client supports OpenSearch 1.x only. Support for 2.x is in progress -- #51.

**Comment by Yury-Fridlyand** [comment]
@brendanjeffreymcmahon,
.Net client v.1.1.0 was released recently, it completely supports OpenSearch 2.0.
Please, re-test and re-open this ticket if it is still relevant.
