### ISSUE TITLE
Investigate license status of generated code

### ISSUE THREAD

**Issue by tfarrep** [opensearch-project/opensearch-net#73]
I'm curious about what legal situation the generated API code is in, as the template outputs the elasticsearch licensing: https://github.com/opensearch-project/opensearch-net/blob/1.0.0/src/ApiGenerator/Views/GeneratorNotice.cshtml#L3-L28

If it's generated does it need to remain licensed to ES? Is the status of the generated code tied to the status of the generator itself? 

Potentially a weird situation if some future API endpoint is entirely unique to OS, but all generated code includes licensing to ES?

_Originally posted by @tfarrep in https://github.com/opensearch-project/opensearch-net/issues/69#issuecomment-1205907561_

**Comment by Yury-Fridlyand** [comment]
The generator wasn't used yet after migration to OpenSearch.

**Comment by dblock** [comment]
I'm taking this.

**Comment by dblock** [comment]
> I'm taking this and will seek guidance accordingly.

Still navigating non-technical folks ;)

**Comment by dblock** [comment]
The general guidance is that we have to keep the license if the generator injects code under ES copyright. What does the generator inject?

**Comment by dblock** [comment]
The official answer is:

_We need to treat this as forked code. We would need to keep the Apache header (could be the standard "SPDX-License-Identifier" one, not the auto-generated one), with Elastic's copyright notice on it.  Once we make additions, we can add our copyright as well, but keep Elastic's too._

Closing this, let's stick to the guideline below.
