### ISSUE TITLE
1.0 Release with dependabot changes

### ISSUE THREAD

**Issue by acarbonetto** [opensearch-project/opensearch-net#74]
Release .NET client 1.0 with the following PR changes:

- [x] https://github.com/opensearch-project/opensearch-net/pull/62
- [x] https://github.com/opensearch-project/opensearch-net/pull/61
- [x] https://github.com/opensearch-project/opensearch-net/pull/60
- [x] https://github.com/opensearch-project/opensearch-net/pull/59
- [x] https://github.com/opensearch-project/opensearch-net/pull/58
- [x] https://github.com/opensearch-project/opensearch-net/pull/57
- [x] Fix backward compatibility tests for archived OpenDistro - related to https://github.com/opensearch-project/opensearch-net/pull/70

PR to complete
---------------
- [x] https://github.com/opensearch-project/opensearch-net/pull/75
- [x] https://github.com/opensearch-project/opensearch-net/issues/81

Release Process
-----------------
https://github.com/opensearch-project/opensearch-net/blob/main/RELEASING.md

- [x] Release branch created for `1.0` release
- [x] Release branch created for the next `1.x` release

**Comment by Yury-Fridlyand** [comment]
Track dependabot recommendation for updating `Newtonsoft.Json` in all projects in #75.

**Comment by Yury-Fridlyand** [comment]
Published on nuget: https://www.nuget.org/profiles/opensearchproject
All tests pass: https://github.com/opensearch-project/opensearch-net/actions?query=branch%3Adev-test-nuget-packages
See test reports attached:
[junit-Tests.Reproduce-NETCoreApp50-test-results.xml.txt](https://github.com/opensearch-project/opensearch-net/files/9305075/junit-Tests.Reproduce-NETCoreApp50-test-results.xml.txt)
[junit-Tests-integration-NETCoreApp50-test-results.xml.txt](https://github.com/opensearch-project/opensearch-net/files/9305076/junit-Tests-integration-NETCoreApp50-test-results.xml.txt)
[junit-Tests-unit-NETCoreApp50-test-results.xml.txt](https://github.com/opensearch-project/opensearch-net/files/9305077/junit-Tests-unit-NETCoreApp50-test-results.xml.txt)

**Comment by Yury-Fridlyand** [comment]
Released: https://github.com/opensearch-project/opensearch-net/releases/tag/v1.0.0
