### ISSUE TITLE
Use abstractions packages published on nuget

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/opensearch-net#77]
Dependency:
- [x] https://github.com/opensearch-project/opensearch-net-abstractions/issues/16

Once abstractions release, we should update references to use nuget packages instead of local ones.

**Comment by MaxKsyunz** [comment]
For context, this will allow us to remove some binaries from this repo.

The packages from [opensearch-project/opensearch-net-abstractions ](https://github.com/opensearch-project/opensearch-net-abstractions) are used in integration tests. At the moment, they are part of the repo.

**Comment by wbeckler** [comment]
Update: the next .net client release is not expected to rely on abstractions as a separate nuget package.

**Comment by Yury-Fridlyand** [comment]
Not relevant since #92 and #86.
