### ISSUE TITLE
Update ADMIN.md and remove 1.0, 1.x, 2.x branches

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/opensearch-net#81]
Issues:

1. Currently Ani and myself are listed in [ADMIN.md](https://github.com/opensearch-project/opensearch-net/blob/main/ADMINS.md#current-admins) but I do not have admin permissions in this repo.

2. `1.0`, `1.x`, `2.x` branches are out of date and might accidentally contain irrelevant commits. We couldn't remove these branches and had to release 1.0.0 client from main branch.

Requesting an admin to help cleaning these 3 branches, and let us know who is repo admin so I can update ADMIN.md accordingly. Thanks

**Comment by CEHENKLE** [comment]
To confirm:  You want to delete 1.0, 1.x and 2.x branches?

**Comment by acarbonetto** [comment]
We want to delete and then re-create these branches to match the 1.0.0 release.

**Comment by VachaShah** [comment]
Looks like I cannot delete them either.

**Comment by joshuali925** [comment]
i think you'll need to temporarily unprotect the branches (if you have admin-level permission)

**Comment by VachaShah** [comment]
Ah right! Just confirming that you want to delete `1.0`, `1.x` and `2.x` branches

**Comment by joshuali925** [comment]
Yes that is correct (I do have a few local backup copies just in case). Also could you let us know who should be in ADMINS.md file for this repo? thanks

**Comment by VachaShah** [comment]
I have deleted the requested branches.

**Comment by Yury-Fridlyand** [comment]
@VachaShah,
Could you delete [dev-test-nuget-packages](https://github.com/opensearch-project/opensearch-net/tree/dev-test-nuget-packages) branch as well? It was used to validate that nuget packages are available for usage.
Thanks
